"""Copy shared Aurora credentials into aiModel/.env for local integration."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
AURORA_ENV = ROOT.parent / "auroraBackend" / ".env"
TARGET = ROOT / ".env"


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def main() -> None:
    aurora = read_env(AURORA_ENV)
    existing = read_env(TARGET)

    mongo_uri = aurora.get("MONGO_URI") or existing.get("MONGO_URI", "")
    jwt_secret = aurora.get("JWT_SECRET") or existing.get("JWT_SECRET", "")
    groq_key = existing.get("GROQ_API_KEY", "")

    shared_keys = (
        "TOKEN_ENCRYPTION_KEY",
        "SELLER_APP_ENCRYPTION_KEY",
        "AMAZON_LWA_CLIENT_ID",
        "AMAZON_LWA_CLIENT_SECRET",
        "AMAZON_ADVERTISING_CLIENT_ID",
        "AMAZON_ADVERTISING_CLIENT_SECRET",
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY",
        "AWS_REGION",
    )

    lines = [
        "# Generated by setup_env.py — do not commit",
        f"MONGO_URI={mongo_uri}",
        "MONGO_DB_NAME=test",
        f"JWT_SECRET={jwt_secret}",
        f"GROQ_API_KEY={groq_key}",
        "FORECASTING_SCHEDULER=0",
        "PORT=8000",
        "AURORA_ORDERS_SOURCE=db",
        "AURORA_DATA_SOURCE=db",
    ]
    for key in shared_keys:
        value = aurora.get(key) or existing.get(key, "")
        if value:
            lines.append(f"{key}={value}")
    lines.append("")
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {TARGET}")
    if not groq_key:
        print("WARNING: GROQ_API_KEY is empty. Add it to aiModel/.env before chatting.")
    if not mongo_uri or not jwt_secret:
        print("WARNING: MONGO_URI or JWT_SECRET missing. Check auroraBackend/.env")
    if not aurora.get("TOKEN_ENCRYPTION_KEY") and not existing.get("TOKEN_ENCRYPTION_KEY"):
        print(
            "WARNING: TOKEN_ENCRYPTION_KEY missing — add it from auroraBackend/.env "
            "or Render so encrypted Amazon refresh tokens can be decrypted."
        )


if __name__ == "__main__":
    main()
